### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by ernieturner** [tangmi/animal-id#1]
This project currently doesn't have a LICENSE file so it's unknown what can be done with this code. Would it be possible to add a license to this so it can safely be used by consuming projects? Thanks!

https://choosealicense.com

**Comment by tangmi** [comment]
It was already MIT, from the `package.json`, but added the LICENSE file as well.

**Comment by ernieturner** [comment]
Sorry, I had forgotten you could specify that in the `package.json` as well. Thanks for adding this!
